pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'Shelter'

include ':app'

include ':setup-wizard-lib'
project(':setup-wizard-lib').projectDir = new File('./libs/SetupWizardLibrary/library')
project(':setup-wizard-lib').buildFileName = 'standalone.gradle'