plugins {
    alias(libs.plugins.android.application)
}

def gitOutput = { List<String> args ->
    try {
        return providers.exec {
            commandLine(['git'] + args)
        }.standardOutput.asText.get().trim()
    }
    catch (ignored) {
        return null
    }
}

def getVersionCode = { ->
    def count = gitOutput(['rev-list', '--first-parent', '--count', 'HEAD'])
    return count != null ? Integer.parseInt(count) : -1
}

def getVersionName = { ->
    return gitOutput(['describe', '--tags', '--dirty'])
}

android {
    namespace = 'net.typeblog.shelter'
    compileSdk = 35

    defaultConfig {
        applicationId = "net.typeblog.shelter"
        minSdk = 24
        targetSdk = 35
        versionCode = getVersionCode()
        versionName = getVersionName()
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    lint {
        disable 'MissingTranslation', 'ExtraTranslation', 'GoogleAppIndexingWarning', 'InvalidFragmentVersionForActivityResult'
    }

    buildFeatures {
        aidl = true
    }
}

androidComponents {
    onVariants(selector().withBuildType('debug')) { variant ->
        variant.outputs.each { output ->
            output.versionCode.set((System.currentTimeMillis() / 1000) as Integer)
        }
    }
}

dependencies {
    implementation libs.androidx.fragment
    implementation libs.androidx.appcompat
    implementation libs.androidx.preference
    implementation libs.androidx.constraintlayout
    implementation libs.material
    implementation libs.androidx.localbroadcastmanager
    implementation libs.androidx.swiperefreshlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.espresso.core
}
